apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: nginx
  namespace: app-example
spec:
  selector:
    matchLabels:
      app: nginx
  endpoints:
  - port: http
    path: /
    interval: 15s
    scrapeTimeout: 5s

